services:
  db:
    image: postgres:15.3-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d dev -U dev"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
